<a href="https://colab.research.google.com/github/Ashwinkpv/DSA-assignment/blob/main/TestingHypothesis_Ashwin.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#import libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 

In [ ]:
# Read Data
salesData=pd.read_csv("/content/Sales_add.csv")
salesData.head()

Month  ... Sales_After_digital_add(in $)
0  Month-1  ...                        270390
1  Month-2  ...                        223334
2  Month-3  ...                        244243
3  Month-4  ...                        231808
4  Month-5  ...                        258402

[5 rows x 5 columns]

### 1) The company wishes to clarify whether there is any increase in sales after stepping into digital marketing

In [ ]:
#Hypothesis
#H0: No increase in sales after stepping into digital marketing. i.e., d = 0

#H1: There is an increase in sales with digital marketing. i.e., d < 0

#Where, d = x-y; d is the difference between sales before digital ad(say x) and sales after the digital ad (say y).


In [ ]:
sales_before_digital_add=np.asarray(salesData['Sales_before_digital_add(in $)'])
sales_after_digital_add=np.asarray(salesData['Sales_After_digital_add(in $)'])
alpha = 0.05

from scipy import stats

t_value,p_value=stats.ttest_rel(sales_before_digital_add,sales_after_digital_add)
t_value,p_value


(-12.09070525287017, 6.336667004575778e-11)

In [ ]:
if one_tailed_p_value<=alpha:

    print('Conclusion','n','Since p-value(=%f)'%one_tailed_p_value,'<','alpha(=%.2f)'%alpha,'''We reject the null hypothesis H0. 

So we conclude that sales have increased by the digital marketing. i.e., d = 0 at %.2f level of significance.'''%alpha)

else:

    print('Conclusion','n','Since p-value(=%f)'%one_tailed_p_value,'>','alpha(=%.2f)'%alpha,'''We do not reject the null hypothesis H0. 

So we conclude that the sales have increased by the digital marketing. i.e., d = 0 at %.2f level of significance.'''%alpha)

Conclusion n Since p-value(=0.000000) < alpha(=0.01) We reject the null hypothesis H0. 

So we conclude that sales have increased by the digital marketing. i.e., d = 0 at 0.01 level of significance.


2) The company needs to check whether there is any dependency between the features “Region” and “Manager”.

In [ ]:
from scipy.stats import chi2_contingency

# defining the table
contingency_table=pd.crosstab(salesData["Region"],salesData["Manager"])
print('contingency_table :-\n',contingency_table)
#Observed Values
Observed_Values = contingency_table.values 
print("Observed Values :-\n",Observed_Values)
b=stats.chi2_contingency(contingency_table)
Expected_Values = b[3]
print("Expected Values :-\n",Expected_Values)
no_of_rows=len(contingency_table.iloc[0:2,0])
no_of_columns=len(contingency_table.iloc[0,0:2])
ddof=(no_of_rows-1)*(no_of_columns-1)
print("Degree of Freedom:-",ddof)
alpha = 0.05
from scipy.stats import chi2
chi_square=sum([(o-e)**2./e for o,e in zip(Observed_Values,Expected_Values)])
chi_square_statistic=chi_square[0]+chi_square[1]
print("chi-square statistic:-",chi_square_statistic)
critical_value=chi2.ppf(q=1-alpha,df=ddof)
print('critical_value:',critical_value)
#p-value
p_value=1-chi2.cdf(x=chi_square_statistic,df=ddof)
print('p-value:',p_value)
print('Significance level: ',alpha)
print('Degree of Freedom: ',ddof)
print('chi-square statistic:',chi_square_statistic)
print('critical_value:',critical_value)
print('p-value:',p_value)
if chi_square_statistic>=critical_value:
    print("Reject H0,There is a relationship between Manager and region")
else:
    print("Retain H0,There is no relationship between Manager and region")
    
if p_value<=alpha:
    print("Reject H0,There is a relationship between Manager and region")
else:
    print("Retain H0,There is no relationship between Manager and region")


contingency_table :-
 Manager     Manager - A  Manager - B  Manager - C
Region                                           
Region - A            4            3            3
Region - B            4            1            2
Region - C            1            3            1
Observed Values :-
 [[4 3 3]
 [4 1 2]
 [1 3 1]]
Expected Values :-
 [[4.09090909 3.18181818 2.72727273]
 [2.86363636 2.22727273 1.90909091]
 [2.04545455 1.59090909 1.36363636]]
Degree of Freedom:- 1
chi-square statistic:- 2.921995464852608
critical_value: 3.841458820694124
p-value: 0.08737974495299139
Significance level:  0.05
Degree of Freedom:  1
chi-square statistic: 2.921995464852608
critical_value: 3.841458820694124
p-value: 0.08737974495299139
Retain H0,There is no relationship between Manager and region
Retain H0,There is no relationship between Manager and region
